import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './components/Footer';
import Header from './components/Header';
import { LeftBar } from './components/LeftBar';
import { ThemeProvider } from './context/ThemeContex';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="flex h-[100vh] w-full flex-col justify-between bg-bgColor">
            <Header />
            <div className="flex h-full flex-row">
              <LeftBar />
              <section className="w-full">{children}</section>
            </div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
